- hosts: dev
  become: true
  tasks:
    - name: Install docker
      apt:
        name: docker
        state: present
        update_cache: 'yes'
    - name: start docker 
      service:
        name: docker
        state: started
        enabled: yes
    - name: Start docker container
      docker_container:
        name: addbook
        image: 'babban27/addbook:{{dockertag}}'
        state: started
        published_ports:
          - '0.0.0.0:8080:8080'

