---
- hosts: dev
  become: true
  tasks:
    - name: Install pip
      apt:
        pkg:
          - python
          - python-pip
          - docker-py
      update_cache: yes
    - name: Start docker container
      docker_container:
        name: addbook
        image: "babban27/addbook:{{dockertag}}"
        state: started
        published_ports:
           - 0.0.0.0:8080:8080
